### ISSUE TITLE
mock-code: allow passing custom hash function via callback

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-testing#48]
Unfortunately, there are simulation codes whose input files are not portable (e.g. because they require the absolute path to some data directory... no idea why).

For such cases, the current hash function will not work on CI since even when the data directory is provided, the absolute path to it will differ.

One might argue that it is really the simulation code that should be rewritten here, but unfortunately that is not always an option.
For such cases, it would be useful to be able to pass a custom hash function to the `mock_code_factory` fixture.

**Comment by greschd** [comment]
I think this issue is closely related to #6 - we should probably combine the discussion.

**Comment by ltalirz** [comment]
Indeed - passing a callback to the standalone executable would be a bit of a pain... pickle pickle

**Comment by ltalirz** [comment]
This has been addressed by @chrisjsewell in a different way in https://github.com/aiidateam/aiida-testing/pull/65 (alternative hasher class is implemented in the test script and loaded dynamically by the mock executable via `importlib`).
