### ISSUE TITLE
consider name change

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-testing#60]
I am not familiar with the genesis of the `aiida-testing`, but it is obviously highly generic and does not convey what functionality the plugin adds on top of what already exists in `aiida-core`.

Some thoughts: The plugin focuses on 
 * tests of processes
 * tests that integrate AiiDA and the simulation software
 * tests that go from setting up calculation inputs through to the final result of the calculation/workflow

Name candidates could therefore be:
 1. `aiida-process-tests`
 2. `aiida-integration-tests`
 3. `aiida-e2e-tests` (e2e=end-to-end)

I would probably vote for option 3

**Comment by greschd** [comment]
> I am not familiar with the genesis of the `aiida-testing`

AFAICR, it was born (mostly) out of the Feb'20 AiiDA Hackathon.

I agree, the name is a bit unfortunate. In particular since it could also be interpreted as "testing" channel for `aiida-core` features. I think it might also be because we might've intended to add more testing-related features, but never did.

Both features of the code relate to speeding up the tests via caching. So maybe, calling it something like `aiida-test-cache` would be appropriate?

It was at one point named `aiida-mock-codes`, but renamed in https://github.com/aiidateam/aiida-testing/commit/525ec6e7ba406f49b0cf3508aa67d32bafa78d4d when the export_cache was added.

**Comment by ltalirz** [comment]
That's true, `aiida-test-cache` sounds good to me as well

**Comment by greschd** [comment]
If we want to be even more specific, `aiida-test-cache-helpers` or `aiida-test-cache-utils` would also work for FMPOV.

@ltalirz feel free to implement the name change (whichever option you think fits best).

**Comment by ltalirz** [comment]
@unkcpz (maybe also @chrisjsewell): you mentioned that you wanted to publish aiida-testing on PyPI.
This means, the time to decide on the name change is now.

I personally would vote for `aiida-test-cache` - I think it is specific and easy to understand.
If you agree, please rename the package before you publish.

**Comment by unkcpz** [comment]
🤔I don't think aiida-test-cache is clear. I personally would vote for aiida-test-helper or more specifically aiida-unittest-helper.

**Comment by ltalirz** [comment]
I would read `aiida-test-cache` as "a plugin that provides a cache for testing", which is exactly what the plugin does.
I guess you read it differently?

I think `aiida-test-helper` is not very specific (the fixtures in aiida-core are also test helpers), and `aiida-unittest-helper` is misleading, since the functionality we provide in this plugin does not target unit tests.

**Comment by unkcpz** [comment]
> I would read aiida-test-cache as "a plugin that provides a cache for testing", which is exactly what the plugin does.
I guess you read it differently?

Yes, I read it differently by regarding "test" as a verb. From your description`aiida-test-cache` makes sense. I have no objection.

> I think aiida-test-helper is not very specific (the fixtures in aiida-core are also test helpers)

That's true. And I really like the helper but for sure `aiida-test-cache-helpers` as @greschd mentioned looks good but might be too long.

**Comment by ltalirz** [comment]
> That's true. And I really like the helper but for sure aiida-test-cache-helpers as @greschd mentioned looks good but might be too long.

Either is fine from my view. I guess users will rarely need to actually import anything from the package, since it can drop its fixtures "magically" into the pytest context [1], so the length of the package name is not of great concern.


[1] https://github.com/aiidateam/aiida-testing/blob/c41027f2c00bb0cdbbf9f13b1024399b5c277dd7/pyproject.toml#L75-L77

**Comment by greschd** [comment]
>  length of the package name is not of great concern

yeah, I think it's better to be a bit more specific with the package name, to avoid the confusion

**Comment by chrisjsewell** [comment]
`aiida-test-cache` is fine by me, no strong feelings on the name

**Comment by chrisjsewell** [comment]
@ltalirz feel free to do the renaming, and then we can get it on pypi 🚀

**Comment by danielhollas** [comment]
I'm planning to do the renaming this week. The only question is, should it be `aiida-test-cache` or `aiida-testcache`? I haven't seen many packages with two dashes, also the import would look a bit weird

```python
import aiida_test_cache
# or
import aiida_testcache
```

Not sure which one is better.

**Comment by danielhollas** [comment]
Could somebody make me a maintainer on Readthedocs? I'm gonna have to rename the package there as were, and point it to the renamed repo.

**Comment by ltalirz** [comment]
I prefer `aiida_test_cache`.

What is your readthedocs username?

**Comment by ltalirz** [comment]
ok, I think I found it ;-)

**Comment by danielhollas** [comment]
Oh sorry, it's `danielhollas` I believe. Thankfully pretty unique I guess. :-D Thanks!

**Comment by greschd** [comment]
@ltalirz @danielhollas it seems I'm still admin, here and on RTD. I don't particularly mind it, but feel free to kick me if you want to do some housekeeping, since I haven't been active here the last 3 years.

**Comment by danielhollas** [comment]
@greschd Thanks for letting us know! I agree from a basic security standpoint it's better to have less admins. I've changed your permissions to "write" so you should still be able to push to the repo, manage issues, PRs etc. 

FYI Here's the current permission list
