### ISSUE TITLE
Release automation

### ISSUE THREAD

**Issue by danielhollas** [aiidateam/aiida-testing#72]
We should have an automated release workflow via GitHub actions, we can use the same thing as other repos in aiidateam.

After that I'd release 0.1 version for the current users to use. Any further (potentially breaking) changes then can go to 0.2 release.

Thoughts?

**Comment by danielhollas** [comment]
Before publishing, we also want to change the name of the package, per discussion in #60. Looks like the discussion converged to `aiida-test-cache`.

**Comment by ltalirz** [comment]
> Before publishing, we also want to change the name of the package, per discussion in #60. Looks like the discussion converged to `aiida-test-cache`.

Fine with me

**Comment by danielhollas** [comment]
It looks like there are only 5 repositories with `aiida-testing` in their dependencies (either as a git dependency or via `aiidalab-testing-dev` package on PYPI). So we can easily create PRs for then once we publish under a new name. We should also somehow yank the `aiidalab-testing-dev` package if possible, and if not at least update its description to point to the new package.

**Comment by danielhollas** [comment]
Should also configure automatic versioning on ReadTheDocs based on tags
https://docs.readthedocs.io/en/stable/guides/automation-rules.html
